### ISSUE TITLE
Upgrade graft to use Backbone 1.1.2

### ISSUE THREAD

**Issue by cerinman** [inlineblock/graft#3]
Hi Dennis,

I'm a new employee at Moneydesktop.  Brandon Beeks sent me your way in hopes of getting Graft upgraded to Backbone version 1.1.2.  I noticed that you already made a fix for passing options as a parameter but I was hoping to make a pull request against Graft to upgrade Backbone.  I attempted to push my branch up but it looks like I don't have permission.  When you get a moment I would appreciate any help you might be able to give.  Thank you.

**Comment by inlineblock** [comment]
@cerinman Fork it with your github account, fix it, make a pull request.
